### ISSUE TITLE
Running release_tag fails when symlink to manageiq is missing in manageiq-content/spec

### ISSUE THREAD

**Issue by simaishi** [ManageIQ/manageiq-release#12]
```
ERROR: The ManageIQ application must be present in spec/manageiq.
  Clone it from GitHub or symlink it from local source.

[!] There was an error parsing `Gemfile`: exit. Bundler cannot continue.

 #  from /home/simaishi/source/manageiq-release/repos/manageiq-content/Gemfile:12
 #  -------------------------------------------
 #    puts "  Clone it from GitHub or symlink it from local source."
 >    exit 1
 #  end
 #  -------------------------------------------
```

The workaround is to manually create the symlink.

**Comment by djberg96** [comment]
@simaishi Is this still an issue?

**Comment by simaishi** [comment]
Just tried it, and it still fails without symlink.

**Comment by Fryguy** [comment]
You should be able to now pass MANAGEIQ_REPO as an env var during the clone phase, and it will create the symlink to that repo during bin/setup.  If the code doesn't do bin/setup though, I'm not sure.

**Comment by Fryguy** [comment]
I think this works now - release_tag will ensure that manageiq is cloned first before others, then ensure the symlinks go to that repo.
