### ISSUE TITLE
When using --repo option, loading config file is skipped

### ISSUE THREAD

**Issue by simaishi** [ManageIQ/manageiq-release#167]
When running a script that takes `--repo` or `--repo-set` option (e.g. release_tag.rb), using `--repo` doesn't load config file and repos are missing options (e.g. has_real_releases, has_rake_release).

**Comment by Fryguy** [comment]
I think this will work now if you set it up so you pass both the repo and repo-set options after https://github.com/ManageIQ/multi_repo/commit/76e195aba5ee88d4fcaf747adcddc9297f1fc98c
